name: fluct
description: A command-lint tool for help develop flutter application.
version: 1.0.2
homepage: https://github.com/rhymelph/fluct
executables:
  fluct:
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
 path: ^1.6.0
 args: ^1.5.2
 cli_util: ^0.1.3+2
 completion: ^0.2.1+1
 yaml: ^2.2.0
 io: ^0.3.3
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
